cwd="/home"
args=[]
userPermission=0
inputMode="command"
path=["/bin","/usr/bin","/root/bin","/usr/local/bin"]
font="/usr/share/fonts/Monospace.font"
osName="Linux"
browserName="Chrome"
userName="browser"
hostName="BrowserLinux"
theme=["white","black","black","14px"]
pipe=""
home="/home"
lastStatus=0